name: Test

permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-main
          - gemfiles/Gemfile-rails-7-0
          - gemfiles/Gemfile-rails-7-1
          - gemfiles/Gemfile-rails-7-2
          - gemfiles/Gemfile-rails-8-0
        ruby:
          - '4.0'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
        orm:
          - active_record
          - mongoid
        exclude:
          - gemfile: Gemfile
            ruby: '3.1'
          - gemfile: Gemfile
            ruby: '3.0'
          - gemfile: Gemfile
            ruby: '2.7'
          - gemfile: gemfiles/Gemfile-rails-main
            ruby: '3.2'
          - gemfile: gemfiles/Gemfile-rails-main
            ruby: '3.1'
          - gemfile: gemfiles/Gemfile-rails-main
            ruby: '3.0'
          - gemfile: gemfiles/Gemfile-rails-main
            ruby: '2.7'
          - gemfile: gemfiles/Gemfile-rails-8-0
            ruby: '3.1'
          - gemfile: gemfiles/Gemfile-rails-8-0
            ruby: '3.0'
          - gemfile: gemfiles/Gemfile-rails-8-0
            ruby: '2.7'
          - gemfile: gemfiles/Gemfile-rails-7-2
            ruby: '3.0'
          - gemfile: gemfiles/Gemfile-rails-7-2
            ruby: '2.7'
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DEVISE_ORM: ${{ matrix.orm }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
      - uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # 1.12.1
        if: ${{ matrix.orm == 'mongoid' }}
      - run: bundle exec rake
